# https://blog.wolt.com/engineering/2021/09/30/professional-grade-mypy-configuration/
[mypy]
exclude = build/
ignore_errors = True
show_error_codes = True

[mypy-tests.test_organizations.*]
# ignore_errors = False

[mypy-moto.organizations.*]
ignore_errors = False
strict = True
